const dctTransLeagues = {
'Argentina|Liga Profesional': '1. argentinská liga',
'Argentina|Primera B': '3. argentinská liga',
'Argentina|Primera Nacional': '2. argentinská liga',
'Australia|A-League': '1. australská liga',
'Australia|NPL Northern NSW': 'Australská NPL, Northern NSW',
'Australia|NPL NSW': 'Australská NPL, New South Wales',
'Australská NPL, Queensland': 'Australia|NPL Queensland',
'Austria|2. Liga': '2. rakouská liga',
'Austria|Bundesliga': '1. rakouská liga',
'Azerbaijan|Premier League': '1. ázerbájdžánská liga',
'Belgium|Challenger Pro League': '2. belgická liga',
'Belgium|Jupiler Pro League': '1. belgická liga',
'Brazil|Carioca': 'Brazílie - Carioca',
'Brazil|Catarinense': 'Brazílie - Catarinense',
'Brazil|Gaucho': 'Brazílie - Gaucho A1',
'Brazil|Paulista': 'Brazílie - Paulista A1',
'Brazil|Pernambucano': 'Brazílie - Pernambucano',
'Bulgaria|efbet League': '1. bulharská liga',
'Colombia|Primera A': '1. kolumbijská liga',
'Costa Rica|Primera Division': '1. kostarická liga',
'Croatia|HNL': '1. chorvatská liga',
'Cyprus|Cyprus League': '1. kyperská liga',
'Czech Republic|Chance Liga': 'Česká Chance Liga',
'Denmark|Superliga': '1. dánská liga',
'Ecuador|Liga Pro': '1. ekvádorská liga',
'El Salvador|Primera Division': '1. salvadorská liga',
'England|Premier League 2': '1. anglická liga U21',
'England|Premier League': '1. anglická liga',
'Finland|Ykkosliigacup': 'Finský ligový pohár 2.ligy',
'France|Ligue 1': '1. francouzská liga',
'Germany|2. Bundesliga': '2. německá liga',
'Germany|3. Liga': '3. německá liga',
'Germany|Bundesliga': '1. německá liga',
'Germany|Regionalliga Nordost': '4. německá liga - Severovýchod',
'Greece|Super League': '1. řecká liga',
'Guatemala|Liga Nacional': '1. guatemalská liga',
'Honduras|Liga Nacional': '1. honduraská liga',
'Hungary|NB I.': '1. maďarská liga',
'Hungary|NB II.': '2. maďarská liga',
'Chile|Liga de Primera': '1. chilská liga',
'India|ISL': '1. indická liga',
'Indonesia|Super League': '1. indonéská liga',
"Israel|Ligat ha'Al": '1. izraelská liga',
'Italy|Serie A': '1. italská liga',
'Italy|Serie B': '2. italská liga',
'Italy|Serie C - Group A': '3. italská liga',
'Italy|Serie C - Group B': '3. italská liga',
'Italy|Serie C - Group C': '3. italská liga',
'Japan|J1 League': 'J1 100 Year Vision League',
'Japan|J2/J3 League': 'J2/J3 League',
'Luxembourg|BGL Ligue': '1. lucemburská liga',
'Malaysia|Super League': '1. malajsijská liga',
'Malta|Premier League': '1. maltská liga',
'Mexico|Liga MX': '1. mexická liga',
'Morocco|Botola Pro': '1. marocká liga',
'Netherlands|Eerste Divisie': '2. nizozemská liga',
'Netherlands|Eredivisie': '1. nizozemská liga',
'Panama|LPF': '1. panamská liga',
'Peru|Liga 1': '1. peruánská liga',
'Poland|Division 1': '2. polská liga',
'Poland|Ekstraklasa': '1. polská liga',
'Portugal|Liga Portugal 2': '2. portugalská liga',
'Portugal|Liga Portugal': '1. portugalská liga',
'Qatar|QSL': '1. katarská liga',
'Romania|Superliga': '1. rumunská liga',
'Scotland|Premiership': '1. skotská liga',
'Serbia|Mozzart Bet Prva Liga': '2. srbská liga',
'Serbia|Mozzart Bet Super Liga': '1. srbská liga',
'Singapore|Premier League': '1. singapurská liga',
'Slovakia|Nike liga': '1. slovenská liga',
'Slovenia|Prva liga': '1. slovinská liga',
'Spain|LaLiga': '1. španělská liga',
'Spain|LaLiga2': '2. španělská liga',
'Spain|Primera RFEF - Group 1': '3. španělská liga',
'Spain|Primera RFEF - Group 2': '3. španělská liga',
'Sweden|Svenska Cupen': 'Švédský pohár',
'Switzerland|Challenge League': '2. švýcarská liga',
'Switzerland|Super League': '1. švýcarská liga',
'Turkey|1. Lig': '2. turecká liga',
'Turkey|Super Lig': '1. turecká liga',
'Ukraine|Premier League': '1. ukrajinská liga',
'United Arab Emirates|UAE League': '1. SAE liga',
'USA|MLS': 'MLS',
'Venezuela|Liga FUTVE': '1. venezuelská liga',
'World|Friendly International': 'Přátelské zápasy',
}
const dctTransTeams = {
'AC Milan': 'AC Milan',
'Academico Viseu': 'Academico Viseu',
'AD Tarma': 'ADT',
'Adamstown Rosebud': 'Adamstown',
'AEK Athens': 'AEK Athens',
'AEK Larnaca': 'AEK Larnaca',
'Aguila': 'Aguila',
'AIK': 'AIK Stockholm',
'Ajka': 'Ajka',
'Al Ahli Doha': 'Al Ahli SC',
'Al Ain': 'Al Ain',
'Al Nasr': 'Al Nasr Dubai',
'Al Rayyan': 'Al Rayyan',
'Al Wakra': 'Al Wakra',
'Alajuelense': 'Alajuelense',
'Albacete': 'Albacete',
'AlbinoLeffe': 'AlbinoLeffe',
'Albirex Niigata': 'Niigata',
'Alcorcon': 'Alcorcón',
'Algeciras': 'Algeciras',
'Alianza Atl.': 'Alianza Atlético Sullana',
'Alianza FC': 'Alianza FC',
'All Boys': 'All Boys',
'Almirante Brown': 'Almirante Brown',
'Al-Sadd': 'Al Sadd',
'Amstetten': 'Amstetten',
'Anderlecht': 'Anderlecht',
'Angers': 'Angers',
'Antalyaspor': 'Antalyaspor',
'Antequera': 'Antequera',
'Antigua': 'Antigua',
'APOEL': 'APOEL Nicosia',
'Arabe Unido': 'Árabe Unido',
'Argentino de Quilmes': 'Argentino de Quilmes',
'Aris': 'Aris Thessaloniki',
'Arka Gdynia': 'Arka Gdynia',
'Arsenal': 'Arsenal',
'Arzignano': 'Arzignano Valchiampo',
'AS Roma': 'AS Roma',
'Ascoli': 'Ascoli',
'Atalanta': 'Atalanta Bergamo',
'Athletic Bilbao W': 'Bilbao Ž',
'Atl. Rafaela': 'Atlético Rafaela',
'Atl. San Luis': 'Atlético San Luis',
'Atlas': 'Atlas Guadalajara',
'Aue': 'Aue',
'Aurora F.C.': 'Aurora FC',
'Austin FC': 'Austin FC',
'Auxerre': 'Auxerre',
'Avellino': 'Avellino',
'Avispa Fukuoka': 'Fukuoka',
'Ayutthaya Utd': 'Ayutthaya United',
'B. Monchengladbach': 'Mönchengladbach',
'Bangkok Utd': 'Bangkok United',
'Bani Yas': 'Bani Yas',
'Barakaldo': 'Barakaldo',
'Basel': 'Basel',
'Beerschot VA': 'Beerschot',
'Bekescsaba 1912': 'Békéscsaba',
'Benevento': 'Benevento',
'Bengaluru FC': 'Bengaluru FC',
'Besiktas': 'Besiktas',
'Beveren': 'Beveren',
'Birmingham U21': 'Birmingham U21',
'Bissen': 'Bissen',
'Boavista': 'Boavista SC',
'Bodrumspor': 'Bodrumspor',
'Bohemians': 'Bohemians 1905',
'Borneo': 'Borneo FC',
'Botafogo RJ': 'Botafogo FR',
'Bra': 'AC Bra',
'Bravo': 'Bravo',
'Brighton U21': 'Brighton U21',
'Brighton W': 'Brighton Ž',
'Brisbane City': 'Brisbane City',
'Brisbane Roar U23': 'Brisbane Roar Youth',
'Brusque': 'Brusque',
'Budafoki': 'Budafoki',
'Burgos CF': 'Burgos CF',
'BVSC-Zuglo': 'BVSC Zugló',
'BW Linz': 'Blau Weiss Linz',
'Cacahuatique': 'Cacahuatique',
'Cacereno': 'Cacereno',
'Cajamarca': 'UTC Cajamarca',
'Campobasso': 'Campobasso',
'Capivariano': 'Capivariano',
'Caracas': 'Caracas',
'Carpi': 'Carpi',
'Cartagines': 'Cartaginés',
'Catania': 'Catania',
'CE Europa': 'CE Europa',
'Celta Vigo': 'Celta Vigo',
'Celtic': 'Celtic Glasgow',
'Central Coast Mariners': 'Central Coast Mariners',
'Central Cordoba': 'Central Córdoba SdE',
'Central Esp.': 'Central Espanol',
'Cerezo Osaka': 'Cerezo',
'CF Montreal': 'Montreal',
'Cienciano': 'Cienciano Cusco',
'Ciudad Bolivar': 'Ciudad de Bolivar',
'Club A. Guemes': 'Güemes',
'Coban Imperial': 'Cobán Imperial',
'Columbus Crew': 'Columbus',
'Comunicaciones': 'Comunicaciones',
'Cooks Hill United': 'Cooks Hill United',
'Coquimbo': 'Coquimbo',
'Corum': 'Corum FK',
'Cosenza': 'Cosenza',
'Cottbus': 'Cottbus',
'Cremonese': 'Cremonese',
'Crotone': 'Crotone',
'Cruz Azul': 'Cruz Azul',
'Crystal Palace': 'Crystal Palace',
'Csakvari': 'Csákvári',
'CSKA 1948 Sofia': 'CSKA 1948 Sofia',
'Cukaricki': 'Cukaricki Beograd',
'Debrecen': 'Debrecen VSC',
'Def. de Belgrano': 'Defensores de Belgrano',
'Degerfors': 'Degerfors',
'Delfin': 'Delfin',
'Dep. Cuenca': 'Deportivo Cuenca',
'Dep. Merlo': 'Deportivo Merlo',
'Deportivo Maipu': 'Deportivo Maipú',
'Dewa United': 'Dewa United',
'Differdange': 'Differdange',
'Din. Zagreb': 'Dinamo Zagreb',
'Diriangen': 'Diriangen',
'Dolomiti Bellunesi': 'Dolomiti Bellunesi',
'DPMM': 'Brunei DPMM',
'Dudelange': 'Dudelange',
'Dukla Prague': 'Dukla Praha',
'Ecuador U20 W': 'Ekvádor Ž-U20',
'Eibar W': 'Eibar Ž',
'Eilenburg': 'Eilenburg',
'Eldense': 'Eldense',
'Elfsborg': 'Elfsborg',
'Estoril': 'Estoril Praia',
'Estudiantes Rio Cuarto': 'Estudiantes Río Cuarto',
'Everton W': 'Everton Ž',
'FAS': 'FAS',
'FC Mamer': 'Mamer',
'Feirense': 'Feirense',
'Felgueiras': 'Felgueiras',
'Feyenoord': 'Feyenoord',
'FK Panevezys': 'FK Panevežys',
'Floriana': 'Floriana',
'Fluminense': 'Fluminense',
'Foggia': 'Foggia',
'Fredericia': 'Fredericia',
'Freiburg': 'Freiburg',
'Fuerte San Francisco': 'Fuerte San Francisco',
'Fulham': 'Fulham',
'FUS Rabat': 'FUS Rabat',
'Gamba Osaka': 'Gamba',
'Gaziantep': 'Gaziantep BB',
'Genk': 'Genk',
'Getafe': 'Getafe',
'Gifu': 'Gifu',
'Gijon': 'Gijón',
'Gil Vicente': 'Gil Vicente',
'Gimnasia Jujuy': 'Gimnasia Jujuy',
'Gimnasia y Tiro': 'Gimnasia Tiro',
'Giugliano': 'Giugliano',
'GKS Katowice': 'GKS Katowice',
'Gnistan': 'Gnistan Helsinki',
'Godoy Cruz': 'Godoy Cruz',
'Goztepe': 'Göztepe',
'Gremio': 'Gremio',
'Groningen': 'Groningen',
'Guadalajara Chivas': 'Chivas Guadalajara',
'Guadalupe': 'Guadalupe FC',
'Guastatoya': 'Guastatoya',
'Gyor': 'Györi ETO',
'Gzira': 'Gzira',
'Hacken': 'Häcken',
'Hajduk Split': 'Hajduk Split',
'Halmstad': 'Halmstad',
'Hannover': 'Hannover',
'Hapoel Haifa': 'Hapoel Haifa',
'Hassania Agadir': 'Hassania Agadir',
'Heidenheim': 'Heidenheim',
'Helsingborg': 'Helsingborg',
'Heracles': 'Heracles',
'Hercules': 'C.D. Hercules',
'Herrera': 'Herrera',
'Hertha Berlin': 'Hertha Berlin',
'Hertha Wels': 'FC HOGO Hertha Wels',
'Hibernian': 'Hibernian',
'Hibernians': 'Hibernians',
'Hoffenheim II': 'Hoffenheim II',
'Honved': 'Honvéd',
'Hostert': 'Hostert',
'Houston Dynamo': 'Houston',
'Chacarita Juniors': 'Chacarita',
'Chaco For Ever': 'Chaco For Ever',
'Chapecoense-SC': 'Chapecoense',
'Charleroi': 'Charleroi',
'Charlestown Azzurri': 'Charlestown Azzurri',
'Charlton W': 'Charlton Ž',
'Chaves': 'Chaves',
'Chelsea W': 'Chelsea Ž',
'Chiba': 'Chiba',
'Chicago Fire': 'Chicago',
'Imabari': 'Imabari',
'Imisli FK': 'Imisli',
'IMT Novi Beograd': 'IMT Novi Beograd',
'Inter Bogotá': 'Inter Bogotá',
'Inter F.A': 'Inter F.A',
'Inter Miami': 'Inter Miami',
'IR Tanger': 'Ittihad Tanger',
'Ituzaingo': 'Ituzaingo',
'Iwaki': 'Iwaki',
'Jamaica': 'Jamajka',
'Jedinstvo U.': 'Jedinstvo Ub',
'Jeunesse Canach': 'Jeunesse Canach',
'Juan Pablo II': 'Juan Pablo II',
'Juticalpa': 'Juticalpa',
'Juve Stabia': 'Juve Stabia',
'Juventud': 'Juventud de Las Piedras',
'Juventude': 'Juventude',
'Juventus U23': 'Juventus Torino Next Gen',
'Kabel Novi Sad': 'Kabel Novi Sad',
'Kagoshima Utd': 'Kagoshima United',
'Kaiserslautern': 'Kaiserslautern',
'Kamatamare': 'Kamatamare',
'Kanazawa': 'Kanazawa',
'KaPa': 'KäPa Helsinki',
'Kapaz': 'Kapaz',
'Karagumruk': 'Karagumruk',
'Karcagi': 'Karcagi',
'Karpaty Lviv': 'Karpaty Lviv',
'Kayserispor': 'Kayserispor',
'Kerala Blasters': 'Kerala Blasters',
'Khorfakkan': 'Khor Fakkan',
'Kifisia': 'Kifisias',
'Kochi United': 'Kochi United',
'Kolos Kovalivka': 'Kolos Kovalivka',
'Kozarmisleny SE': 'Kozármisleny',
'Kuala Lumpur City': 'Kuala Lumpur City FC',
'Kuching City FC': 'Kuching City FC',
'KV Mechelen': 'KV Mechelen',
'Kyoto': 'Kyoto',
'La Serena': 'La Serena',
'Lahti': 'FC Lahti',
'LASK': 'LASK Linz',
'Lausanne Ouchy': 'Lausanne Ouchy',
'Lausanne': 'Lausanne',
'Le Havre': 'Le Havre',
'Lecco': 'Lecco',
'Leones del Norte': 'Leones del Norte',
'Levadiakos': 'Levadiakos',
'Levante': 'Levante',
'Levski Sofia': 'Levski Sofia',
'Liberec W': 'Liberec Ž',
'Liberia': 'Liberia',
'Lille': 'Lille',
'Lion City': 'Lion City Sailors',
'Liverpool W': 'Liverpool Ž',
'Liverpool': 'Liverpool',
'Livingston': 'Livingston',
'Lokomotive Leipzig': 'Loko Leipzig',
'Lorient': 'Lorient',
'Los Andes': 'Los Andes',
'Los Angeles FC': 'Los Angeles FC',
'Los Chankas': 'Los Chankas',
'Lugano': 'Lugano',
'Luis Angel Firpo': 'Luis Angel Firpo',
'Lumezzane': 'Lumezzane',
'Lusitania FC': 'Lusitania Lourosa',
'Luzern': 'Luzern',
'Lyon': 'Lyon',
'Maastricht': 'Maastricht',
'Macara': 'Macará',
'Macarthur FC': 'Macarthur FC',
'Macva': 'Mačva Šabac',
'Maitland': 'Maitland',
'Malaga': 'Málaga',
'Mallorca': 'Mallorca',
'Malmo FF': 'Malmö FF',
'Managua FC': 'FC Managua',
'Manchester Utd W': 'Manchester United Ž',
'Manisa FK': 'Manisa FK',
'Marathon': 'Marathón',
'Marbella': 'Marbella',
'Marconi Stallions': 'Marconi Stallions',
'Maribor': 'Maribor',
'Marquense': 'Marquense',
'Martinique': 'Martinique',
'Meuselwitz': 'Meuselwitz',
'Mezokovesd-Zsory': 'Mezökövesd',
'Mictlan': 'Mictlán',
'Midland': 'Ferrocarril Midland',
'Midtjylland': 'Midtjylland',
'Millonarios': 'Millonarios',
'Minnesota United': 'Minnesota United',
'Mito': 'Mito',
'Mlada Boleslav': 'Mladá Boleslav',
'Modena': 'Modena',
'Mondorf': 'Mondorf',
'Monopoli': 'Monopoli',
'Mosta': 'Mosta',
'Muang Thong Utd': 'Muangthong United',
'Mumbai City': 'Mumbai City FC',
'Municipal Limeno': 'Municipal Limeno',
'Municipal': 'Municipal',
'Nantes': 'Nantes',
'Napoli': 'Napoli',
'Nashville SC': 'Nashville SC',
'Necaxa': 'Necaxa',
'New England Revolution': 'New England',
'New York Red Bulls': 'New York RB',
'Newcastle Jets': 'Newcastle Jets',
'Nice': 'Nice',
'Niedercorn': 'Progres Niederkorn',
'North East Utd': 'Northeast United',
'Nottingham': 'Nottingham',
'Novorizontino': 'Novorizontino',
'Oddevold': 'Oddevold',
'Odra Opole': 'Odra Opole',
'OFI Crete': 'OFI Crete',
'Okayama': 'Okayama',
'Olancho': 'Olancho FC',
'Omonia Aradippou': 'Omonia Aradippou',
'Omonia': 'Omonia Nicosia',
'Orgryte': 'Örgryte',
'Orlando City': 'Orlando City',
'Osaka': 'FC Osaka',
'Osasuna B': 'Osasuna B',
'Ospitaletto': 'ACD Ospitaletto',
'Ostrava': 'Ostrava',
'Ourense CF': 'Ourense CF',
'Oxford Utd W': 'Oxford United Ž',
'Paderborn': 'Paderborn',
'Paks': 'Paksi',
'Palmeiras': 'Palmeiras',
'Panathinaikos': 'Panathinaikos',
'Panserraikos': 'Panserraikos Serres',
'Parma': 'Parma',
'Pathum United': 'BG Pathum United',
'Patro Eisden': 'Patro Eisden',
'Patronato': 'Patronato',
'Penafiel': 'Penafiel',
'Persib Bandung': 'Persib Bandung',
'Persita': 'Persita Tangerang',
'Philadelphia Union': 'Philadelphia Union',
'Platense': 'Platense',
'Plaza Amador': 'Plaza Amador',
'Plzen W': 'Plzeň Ž',
'Plzen': 'Plzeň',
'Pogon Siedlce': 'Pogoň Siedlce',
'Polissya Zhytomyr': 'Polissya Zhytomyr',
'Polonia Bytom': 'Polonia Bytom',
'Pontedera': 'Pontedera',
'Portimonense': 'Portimonense',
'Pro Patria': 'Pro Patria',
'Pro Vercelli': 'Pro Vercelli',
'Puntarenas FC': 'Puntarenas',
'Quilmes': 'Quilmes',
'Racing Santander': 'Racing Santander',
'Radnicki Nis': 'Radnicki Nis',
'Radomiak Radom': 'Radomiak Radom',
'Raja Casablanca': 'Raja Casablanca',
'Randers FC': 'Randers Freja',
'Rangers': 'Glasgow Rangers',
'Real Pilar': 'Real Pilar',
'Real Salt Lake': 'Salt Lake',
'Reggiana': 'Reggiana',
'Renaissance Zemamra': 'Renaissance Zemamra',
'Rennes': 'Rennes',
'Renofa Yamaguchi': 'Yamaguchi',
'Ried': 'Ried',
'Rijeka': 'Rijeka',
'River Plate': 'River Plate',
'Roda': 'Roda Kerkrade',
'Rodange': 'Rodange',
'Ruzomberok': 'Ružomberok',
'RWDM Brussels': 'Daring Brussels',
'S. Rzeszow': 'Stal Rzeszów',
'Sabadell': 'Sabadell',
'Sabah Baku': 'Sabah FK',
'Salernitana': 'Salernitana',
'Salzburg': 'Salzburg',
'Samsunspor': 'Samsunspor',
'San Diego FC': 'San Diego FC',
'San Jose Earthquakes': 'San Jose',
'San Lorenzo': 'San Lorenzo',
'San Martin Burzaco': 'San Martin Burzaco',
'San Martin S.J.': 'San Martín San Juan',
'San Telmo': 'San Telmo',
'Sanfrecce Hiroshima': 'Sanfrecce Hiroshima',
'Sanluqueno': 'Sanluqueno',
'Santa Cruz': 'Santa Cruz',
'Santos Laguna': 'Santos Laguna',
'Santos': 'Santos',
'Saprissa': 'Saprissa',
'SC Farense': 'Farense',
'Selangor': 'Selangor',
'Sevilla': 'FC Sevilla',
'SG Dynamo Dresden': 'Dynamo Dresden',
'Shakhtar Donetsk': 'Shakhtar Donetsk',
'Shamakhi': 'Shamakhi FK',
'Sheffield Utd': 'Sheffield United',
'Sheffield Wed': 'Sheffield Wednesday',
'Sigma Olomouc': 'Olomouc',
'Silkeborg': 'Silkeborg',
'Sion': 'Sion',
'Siracusa': 'Siracusa',
'Siroki Brijeg': 'Široki Brijeg',
'SJK Akatemia': 'SJK Akatemia',
'Slask Wroclaw': 'Slask Wroclaw',
'Slovan Bratislava': 'Slovan Bratislava',
'Smederevo': 'Smederevo',
'Soroksar': 'Soroksár',
'Sorrento': 'Sorrento',
'Sparta Prague': 'Sparta Praha',
'Sparta Rotterdam': 'Sparta Rotterdam',
'Sport Huancayo': 'Sport Huancayo',
'Sporting FC': 'Sporting San José',
'Sporting Kansas City': 'Kansas',
'Sportivo Italiano': 'Sportivo Italiano',
'St. George City': 'St. George City',
'St. Liege': 'St. Liege',
'St. Pauli': 'St. Pauli',
'Strasbourg': 'Strasbourg',
'Sturm Graz': 'Sturm Graz',
'Stuttgart': 'Stuttgart',
'Suduva': 'Suduva Marijampole',
'Sunderland': 'Sunderland',
'Sydney Olympic': 'Sydney Olympic FC',
'Szeged': 'Szeged-Csanád',
'Szentlorinc': 'Szentlörinc',
'Talleres (R.E)': 'Talleres Remedios de Escalada',
'Tampines': 'Tampines',
'Telstar': 'Telstar',
'Teplice': 'Teplice',
'Teruel': 'Teruel',
'Tigre': 'Tigre',
'Tiszakecske': 'Tiszakécske',
'Tochigi City': 'Tochigi City',
'Tochigi SC': 'Tochigi SC',
'Toluca': 'Toluca',
'Tottenham': 'Tottenham',
'Trabzonspor': 'Trabzonspor',
'Trelleborg': 'Trelleborg FF',
'Trento': 'Trento',
'TSC': 'TSC Bačka Topola',
'Twente': 'Twente',
'U. De Concepcion': 'Universidad de Concepcion',
'UD Ibiza': 'UD Ibiza',
'Umraniyespor': 'Umraniyespor',
'UNA Strassen': 'UNA Strassen',
'Union Cocle': 'Union Cocle',
'Unirea Slobozia': 'Unirea Slobozia',
'Univ. Craiova': 'CS Universitatea Craiova',
'Universidad Central': 'Universidad Central',
'Utrecht': 'Utrecht',
'Vaduz': 'Vaduz',
'Valencia': 'Valencia',
'Valladolid': 'Valladolid',
'Vancouver Whitecaps': 'Vancouver',
'Varberg': 'Varberg FC',
'Varnamo': 'Värnamo',
'Vasas': 'Vasas',
'Vasco': 'Vasco',
'Vasteras SK': 'Västeras SK',
'Vegalta Sendai': 'Vegalta Sendai',
'Velez Sarsfield': 'Vélez Sarsfield',
'Venezuela U20 W': 'Venezuela Ž-U20',
'Viborg': 'Viborg',
'Victoria Rosport': 'Victoria Rosport',
'Viktoria Koln': 'Viktoria Köln',
'Villa Dalmine': 'Villa Dálmine',
'Villa San Carlos': 'Villa San Carlos',
'Villarreal': 'Villarreal',
'Volos': 'Volos NFC',
'Vozdovac': 'Vozdovac',
'Waregem': 'Waregem',
'Werder Bremen': 'Bremen',
'West Ham W': 'West Ham Ž',
'Westerlo': 'Westerlo',
'Wil': 'Wil',
'Wollongong Wolves': 'Wollongong Wolves',
'Wolves': 'Wolverhampton',
'WS Wanderers U21': 'Western Sydney W.Youth',
'WS Wanderers': 'Western Sydney',
'Xamax': 'Neuchatel Xamax',
'Young Boys': 'Young Boys Bern',
'Zacatecoluca': 'Zacatecoluca FC',
'Zalaegerszegi': 'Zalaegerszegi',
'Zaragoza': 'Zaragoza',
'Zeledon': 'Zeledón',
'Zemun': 'Zemun',
'Zrinjski': 'Zrinjski Mostar',
'Zwickau': 'Zwickau',
'Zwolle': 'Zwolle',
}

const dctTeamsCZToOP = {
'AGF Aarhus': 'Aarhus',
'AC Milan': 'AC Milan',
'Academico Viseu': 'Academico Viseu',
'Mérida': 'AD Merida',
'ADT': 'AD Tarma',
'Adamstown': 'Adamstown Rosebud',
'AEK Athens': 'AEK Athens',
'AEK Larnaca': 'AEK Larnaca',
'Aguila': 'Aguila',
'AIK Stockholm': 'AIK',
'Ajka': 'Ajka',
'Al Ahli SC': 'Al Ahli Doha',
'Al Ain': 'Al Ain',
'Al Nasr Dubai': 'Al Nasr',
'Al Rayyan': 'Al Rayyan',
'Al Wakra': 'Al Wakra',
'Alajuelense': 'Alajuelense',
'Albacete': 'Albacete',
'AlbinoLeffe': 'AlbinoLeffe',
'Niigata': 'Albirex Niigata',
'Alcorcón': 'Alcorcon',
'Algeciras': 'Algeciras',
'Alianza Atlético Sullana': 'Alianza Atl.',
'Alianza FC': 'Alianza FC',
'All Boys': 'All Boys',
'Almirante Brown': 'Almirante Brown',
'Al Sadd': 'Al-Sadd',
'Team Altamura': 'Altamura',
'Amstetten': 'Amstetten',
'Anderlecht': 'Anderlecht',
'FC Andorra': 'Andorra',
'Angers': 'Angers',
'Antalyaspor': 'Antalyaspor',
'Antequera': 'Antequera',
'Antigua': 'Antigua',
'APOEL Nicosia': 'APOEL',
'Árabe Unido': 'Arabe Unido',
'Argentino de Quilmes': 'Argentino de Quilmes',
'Aris Thessaloniki': 'Aris',
'Arka Gdynia': 'Arka Gdynia',
'Arsenal': 'Arsenal',
'Arzignano Valchiampo': 'Arzignano',
'AS Roma': 'AS Roma',
'Ascoli': 'Ascoli',
'Atalanta Bergamo': 'Atalanta',
'Atalanta Bergamo U23': 'Atalanta U23',
'Bilbao Ž': 'Athletic Bilbao W',
'Atlético Rafaela': 'Atl. Rafaela',
'Atlético San Luis': 'Atl. San Luis',
'Atlas Guadalajara': 'Atlas',
'Aue': 'Aue',
'Aurora FC': 'Aurora F.C.',
'Austin FC': 'Austin FC',
'Auxerre': 'Auxerre',
'Avellino': 'Avellino',
'Fukuoka': 'Avispa Fukuoka',
'Ayutthaya United': 'Ayutthaya Utd',
'Alkmaar': 'AZ Alkmaar',
'Mönchengladbach': 'B. Monchengladbach',
'Bangkok United': 'Bangkok Utd',
'Bani Yas': 'Bani Yas',
'Barakaldo': 'Barakaldo',
'FC Barcelona': 'Barcelona',
'Basel': 'Basel',
'Beerschot': 'Beerschot VA',
'Békéscsaba': 'Bekescsaba 1912',
'Benevento': 'Benevento',
'Bengaluru FC': 'Bengaluru FC',
'RSB Berkane': 'Berkane',
'Besiktas': 'Besiktas',
'Beveren': 'Beveren',
'Birmingham U21': 'Birmingham U21',
'Bissen': 'Bissen',
'Boavista SC': 'Boavista',
'Bodrumspor': 'Bodrumspor',
'Bohemians 1905': 'Bohemians',
'Borneo FC': 'Borneo',
'Botafogo FR': 'Botafogo RJ',
'AC Bra': 'Bra',
'Bravo': 'Bravo',
'Union Brescia': 'Brescia',
'Brighton U21': 'Brighton U21',
'Brighton Ž': 'Brighton W',
'Brisbane City': 'Brisbane City',
'Brisbane Roar Youth': 'Brisbane Roar U23',
'Brusque': 'Brusque',
'Budafoki': 'Budafoki',
'Burgos CF': 'Burgos CF',
'BVSC Zugló': 'BVSC-Zuglo',
'Blau Weiss Linz': 'BW Linz',
'Cacahuatique': 'Cacahuatique',
'Cacereno': 'Cacereno',
'UTC Cajamarca': 'Cajamarca',
'Campobasso': 'Campobasso',
'Capivariano': 'Capivariano',
'Caracas': 'Caracas',
'Carpi': 'Carpi',
'Cartaginés': 'Cartagines',
'Catania': 'Catania',
'CE Europa': 'CE Europa',
'Celta Vigo': 'Celta Vigo',
'Celtic Glasgow': 'Celtic',
'Central Coast Mariners': 'Central Coast Mariners',
'Central Córdoba SdE': 'Central Cordoba',
'Central Espanol': 'Central Esp.',
'Cerezo': 'Cerezo Osaka',
'Montreal': 'CF Montreal',
'Cienciano Cusco': 'Cienciano',
'Ciudad de Bolivar': 'Ciudad Bolivar',
'Güemes': 'Club A. Guemes',
'León': 'Club Leon',
'Cobán Imperial': 'Coban Imperial',
'Columbus': 'Columbus Crew',
'Comunicaciones': 'Comunicaciones',
'Cooks Hill United': 'Cooks Hill United',
'Coquimbo': 'Coquimbo',
'Corum FK': 'Corum',
'Cosenza': 'Cosenza',
'Cottbus': 'Cottbus',
'Cremonese': 'Cremonese',
'Crotone': 'Crotone',
'Cruz Azul': 'Cruz Azul',
'Crystal Palace': 'Crystal Palace',
'Csákvári': 'Csakvari',
'CSKA 1948 Sofia': 'CSKA 1948 Sofia',
'Cukaricki Beograd': 'Cukaricki',
'Washington': 'DC United',
'Debrecen VSC': 'Debrecen',
'Defensores de Belgrano': 'Def. de Belgrano',
'Degerfors': 'Degerfors',
'Delfin': 'Delfin',
'Deportivo Cuenca': 'Dep. Cuenca',
'Deportivo Merlo': 'Dep. Merlo',
'Deportivo Maipú': 'Deportivo Maipu',
'Dewa United': 'Dewa United',
'Differdange': 'Differdange',
'Dinamo Zagreb': 'Din. Zagreb',
'Diriangen': 'Diriangen',
'Dolomiti Bellunesi': 'Dolomiti Bellunesi',
'Brunei DPMM': 'DPMM',
'Dudelange': 'Dudelange',
'Dukla Praha': 'Dukla Prague',
'Ekvádor Ž-U20': 'Ecuador U20 W',
'Eibar Ž': 'Eibar W',
'Eilenburg': 'Eilenburg',
'Eldense': 'Eldense',
'Elfsborg': 'Elfsborg',
'Estoril Praia': 'Estoril',
'Estudiantes Río Cuarto': 'Estudiantes Rio Cuarto',
'Everton Ž': 'Everton W',
'FAS': 'FAS',
'Mamer': 'FC Mamer',
'Feirense': 'Feirense',
'Felgueiras': 'Felgueiras',
'Feyenoord': 'Feyenoord',
'FK Panevežys': 'FK Panevezys',
'Floriana': 'Floriana',
'Fluminense': 'Fluminense',
'Foggia': 'Foggia',
'Fredericia': 'Fredericia',
'Freiburg': 'Freiburg',
'Fuerte San Francisco': 'Fuerte San Francisco',
'Fulham': 'Fulham',
'FUS Rabat': 'FUS Rabat',
'Ahead Eagles': 'G.A. Eagles',
'Gamba': 'Gamba Osaka',
'Gaziantep BB': 'Gaziantep',
'Genk': 'Genk',
'Getafe': 'Getafe',
'Gifu': 'Gifu',
'Gijón': 'Gijon',
'Gil Vicente': 'Gil Vicente',
'Gimnasia Jujuy': 'Gimnasia Jujuy',
'Gimnasia Tiro': 'Gimnasia y Tiro',
'Giugliano': 'Giugliano',
'GKS Katowice': 'GKS Katowice',
'Gnistan Helsinki': 'Gnistan',
'Godoy Cruz': 'Godoy Cruz',
'Göztepe': 'Goztepe',
'Atlético Grau': 'Grau',
'Gremio': 'Gremio',
'Groningen': 'Groningen',
'CD Guadalajara': 'Guadalajara',
'Chivas Guadalajara': 'Guadalajara Chivas',
'Guadalupe FC': 'Guadalupe',
'Guastatoya': 'Guastatoya',
'Györi ETO': 'Gyor',
'Gzira': 'Gzira',
'Hapoel Beer Sheva': 'H. Beer Sheva',
'Häcken': 'Hacken',
'Hajduk Split': 'Hajduk Split',
'Halmstad': 'Halmstad',
'Hannover': 'Hannover',
'Hapoel Haifa': 'Hapoel Haifa',
'Hassania Agadir': 'Hassania Agadir',
'Heidenheim': 'Heidenheim',
'Helsingborg': 'Helsingborg',
'Heracles': 'Heracles',
'C.D. Hercules': 'Hercules',
'Herrera': 'Herrera',
'Hertha Berlin': 'Hertha Berlin',
'FC HOGO Hertha Wels': 'Hertha Wels',
'Hibernian': 'Hibernian',
'Hibernians': 'Hibernians',
'Hoffenheim II': 'Hoffenheim II',
'Honvéd': 'Honved',
'Hostert': 'Hostert',
'Houston': 'Houston Dynamo',
'Chacarita': 'Chacarita Juniors',
'Chaco For Ever': 'Chaco For Ever',
'Chapecoense': 'Chapecoense-SC',
'Charleroi': 'Charleroi',
'Charlestown Azzurri': 'Charlestown Azzurri',
'Charlton Ž': 'Charlton W',
'Chaves': 'Chaves',
'Chelsea Ž': 'Chelsea W',
'Chiba': 'Chiba',
'Chicago': 'Chicago Fire',
'Imabari': 'Imabari',
'Imisli': 'Imisli FK',
'IMT Novi Beograd': 'IMT Novi Beograd',
'Inter Bogotá': 'Inter Bogotá',
'Inter F.A': 'Inter F.A',
'Inter Miami': 'Inter Miami',
'Ittihad Tanger': 'IR Tanger',
'Ituzaingo': 'Ituzaingo',
'Iwaki': 'Iwaki',
'Bialystok': 'Jagiellonia',
'Jamajka': 'Jamaica',
'Jedinstvo Ub': 'Jedinstvo U.',
'Jeunesse Canach': 'Jeunesse Canach',
'Juan Pablo II': 'Juan Pablo II',
'Juticalpa': 'Juticalpa',
'Juve Stabia': 'Juve Stabia',
'Juventud de Las Piedras': 'Juventud',
'Juventude': 'Juventude',
'Juventus Torino Next Gen': 'Juventus U23',
'Kabel Novi Sad': 'Kabel Novi Sad',
'Kagoshima United': 'Kagoshima Utd',
'Kaiserslautern': 'Kaiserslautern',
'Kamatamare': 'Kamatamare',
'Kanazawa': 'Kanazawa',
'KäPa Helsinki': 'KaPa',
'Kapaz': 'Kapaz',
'Karagumruk': 'Karagumruk',
'Karcagi': 'Karcagi',
'IF Karlstad': 'Karlstad',
'Karpaty Lviv': 'Karpaty Lviv',
'Kayserispor': 'Kayserispor',
'Kerala Blasters': 'Kerala Blasters',
'Khor Fakkan': 'Khorfakkan',
'Kifisias': 'Kifisia',
'Kochi United': 'Kochi United',
'Kolos Kovalivka': 'Kolos Kovalivka',
'Kozármisleny': 'Kozarmisleny SE',
'Kuala Lumpur City FC': 'Kuala Lumpur City',
'Kuching City FC': 'Kuching City FC',
'KV Mechelen': 'KV Mechelen',
'Kyoto': 'Kyoto',
'La Serena': 'La Serena',
'FC Lahti': 'Lahti',
'LASK Linz': 'LASK',
'Lausanne': 'Lausanne',
'Lausanne Ouchy': 'Lausanne Ouchy',
'Le Havre': 'Le Havre',
'Lecco': 'Lecco',
'Leones del Norte': 'Leones del Norte',
'Levadiakos': 'Levadiakos',
'Levante': 'Levante',
'Levski Sofia': 'Levski Sofia',
'Liberec Ž': 'Liberec W',
'Liberia': 'Liberia',
'Lille': 'Lille',
'CSD Liniers': 'Liniers',
'Lion City Sailors': 'Lion City',
'Liverpool': 'Liverpool',
'Liverpool Ž': 'Liverpool W',
'Livingston': 'Livingston',
'Loko Leipzig': 'Lokomotive Leipzig',
'Lorient': 'Lorient',
'Los Andes': 'Los Andes',
'Los Angeles FC': 'Los Angeles FC',
'Los Chankas': 'Los Chankas',
'Lugano': 'Lugano',
'Luis Angel Firpo': 'Luis Angel Firpo',
'Lumezzane': 'Lumezzane',
'Lusitania Lourosa': 'Lusitania FC',
'Luzern': 'Luzern',
'Lyon': 'Lyon',
'Maastricht': 'Maastricht',
'Macará': 'Macara',
'Macarthur FC': 'Macarthur FC',
'Mačva Šabac': 'Macva',
'Maitland': 'Maitland',
'Málaga': 'Malaga',
'Mallorca': 'Mallorca',
'Malmö FF': 'Malmo FF',
'FC Managua': 'Managua FC',
'Manchester United Ž': 'Manchester Utd W',
'Manisa FK': 'Manisa FK',
'Marathón': 'Marathon',
'Marbella': 'Marbella',
'Marconi Stallions': 'Marconi Stallions',
'Maribor': 'Maribor',
'Marquense': 'Marquense',
'Martinique': 'Martinique',
'Meuselwitz': 'Meuselwitz',
'Mezökövesd': 'Mezokovesd-Zsory',
'Mictlán': 'Mictlan',
'Ferrocarril Midland': 'Midland',
'Midtjylland': 'Midtjylland',
'Millonarios': 'Millonarios',
'Minnesota United': 'Minnesota United',
'Mito': 'Mito',
'Mladá Boleslav': 'Mlada Boleslav',
'Modena': 'Modena',
'Mondorf': 'Mondorf',
'Monopoli': 'Monopoli',
'Mosta': 'Mosta',
'Muangthong United': 'Muang Thong Utd',
'Mumbai City FC': 'Mumbai City',
'Municipal': 'Municipal',
'Municipal Limeno': 'Municipal Limeno',
'Nantes': 'Nantes',
'Napoli': 'Napoli',
'Nashville SC': 'Nashville SC',
'Náutico': 'Nautico',
'Necaxa': 'Necaxa',
'New England': 'New England Revolution',
'New York RB': 'New York Red Bulls',
'Newcastle Jets': 'Newcastle Jets',
'Nice': 'Nice',
'Progres Niederkorn': 'Niedercorn',
'Northeast United': 'North East Utd',
'Nottingham': 'Nottingham',
'Novorizontino': 'Novorizontino',
'Oddevold': 'Oddevold',
'Odra Opole': 'Odra Opole',
'OFI Crete': 'OFI Crete',
'Okayama': 'Okayama',
'Olancho FC': 'Olancho',
'Omonia Nicosia': 'Omonia',
'Omonia Aradippou': 'Omonia Aradippou',
'Örgryte': 'Orgryte',
'Orlando City': 'Orlando City',
'FC Osaka': 'Osaka',
'Osasuna B': 'Osasuna B',
'ACD Ospitaletto': 'Ospitaletto',
'Ostrava': 'Ostrava',
'Ourense CF': 'Ourense CF',
'Oxford United Ž': 'Oxford Utd W',
'Paderborn': 'Paderborn',
'Paksi': 'Paks',
'Palmeiras': 'Palmeiras',
'Panathinaikos': 'Panathinaikos',
'Panserraikos Serres': 'Panserraikos',
'Parma': 'Parma',
'BG Pathum United': 'Pathum United',
'Patro Eisden': 'Patro Eisden',
'Patronato': 'Patronato',
'Penafiel': 'Penafiel',
'Persib Bandung': 'Persib Bandung',
'Persita Tangerang': 'Persita',
'Philadelphia Union': 'Philadelphia Union',
'Platense': 'Platense',
'Plaza Amador': 'Plaza Amador',
'Plzeň': 'Plzen',
'Plzeň Ž': 'Plzen W',
'Pogoň Siedlce': 'Pogon Siedlce',
'Polissya Zhytomyr': 'Polissya Zhytomyr',
'Polonia Bytom': 'Polonia Bytom',
'Pontedera': 'Pontedera',
'Portimonense': 'Portimonense',
'Portland': 'Portland Timbers',
'Münster': 'Preussen Munster',
'Pro Patria': 'Pro Patria',
'Pro Vercelli': 'Pro Vercelli',
'Puntarenas': 'Puntarenas FC',
'Puszcza Niepolomice': 'Puszcza',
'Quilmes': 'Quilmes',
'La Louviere': 'RAAL La Louviere',
'Racing Santander': 'Racing Santander',
'Radnicki Nis': 'Radnicki Nis',
'Radomiak Radom': 'Radomiak Radom',
'Raja Casablanca': 'Raja Casablanca',
'Randers Freja': 'Randers FC',
'Glasgow Rangers': 'Rangers',
'Real Pilar': 'Real Pilar',
'Salt Lake': 'Real Salt Lake',
'Reggiana': 'Reggiana',
'Renaissance Zemamra': 'Renaissance Zemamra',
'Rennes': 'Rennes',
'Yamaguchi': 'Renofa Yamaguchi',
'Ried': 'Ried',
'Rijeka': 'Rijeka',
'River Plate': 'River Plate',
'Roda Kerkrade': 'Roda',
'Rodange': 'Rodange',
'Ružomberok': 'Ruzomberok',
'Daring Brussels': 'RWDM Brussels',
'Stal Rzeszów': 'S. Rzeszow',
'Sabadell': 'Sabadell',
'Sabah FK': 'Sabah Baku',
'Salernitana': 'Salernitana',
'Salzburg': 'Salzburg',
'Samsunspor': 'Samsunspor',
'San Diego FC': 'San Diego FC',
'San Jose': 'San Jose Earthquakes',
'San Lorenzo': 'San Lorenzo',
'San Martin Burzaco': 'San Martin Burzaco',
'San Martín San Juan': 'San Martin S.J.',
'San Telmo': 'San Telmo',
'Sanfrecce Hiroshima': 'Sanfrecce Hiroshima',
'Sanluqueno': 'Sanluqueno',
'Santa Cruz': 'Santa Cruz',
'Santos': 'Santos',
'Santos Laguna': 'Santos Laguna',
'Saprissa': 'Saprissa',
'Farense': 'SC Farense',
'Selangor': 'Selangor',
'FC Sevilla': 'Sevilla',
'Dynamo Dresden': 'SG Dynamo Dresden',
'Shakhtar Donetsk': 'Shakhtar Donetsk',
'Shamakhi FK': 'Shamakhi',
'Sheffield United': 'Sheffield Utd',
'Sheffield Wednesday': 'Sheffield Wed',
'Olomouc': 'Sigma Olomouc',
'Silkeborg': 'Silkeborg',
'Sion': 'Sion',
'Siracusa': 'Siracusa',
'Široki Brijeg': 'Siroki Brijeg',
'SJK Akatemia': 'SJK Akatemia',
'Slask Wroclaw': 'Slask Wroclaw',
'Slovan Bratislava': 'Slovan Bratislava',
'Smederevo': 'Smederevo',
'Soroksár': 'Soroksar',
'Sorrento': 'Sorrento',
'Sparta Praha': 'Sparta Prague',
'Sparta Rotterdam': 'Sparta Rotterdam',
'Sport Huancayo': 'Sport Huancayo',
'Sporting San José': 'Sporting FC',
'Kansas': 'Sporting Kansas City',
'Sportivo Italiano': 'Sportivo Italiano',
'St. George City': 'St. George City',
'St. Liege': 'St. Liege',
'St. Pauli': 'St. Pauli',
'Strasbourg': 'Strasbourg',
'Sturm Graz': 'Sturm Graz',
'Stuttgart': 'Stuttgart',
'Suduva Marijampole': 'Suduva',
'Sunderland': 'Sunderland',
'Sydney Olympic FC': 'Sydney Olympic',
'Sydney United 58': 'Sydney Utd',
'Szeged-Csanád': 'Szeged',
'Szentlörinc': 'Szentlorinc',
'Talleres Remedios de Escalada': 'Talleres (R.E)',
'Tampines': 'Tampines',
'Telstar': 'Telstar',
'Teplice': 'Teplice',
'Teruel': 'Teruel',
'Tigre': 'Tigre',
'WSG Tirol': 'Tirol',
'Tiszakécske': 'Tiszakecske',
'Tochigi City': 'Tochigi City',
'Tochigi SC': 'Tochigi SC',
'Toluca': 'Toluca',
'Tottenham': 'Tottenham',
'Trabzonspor': 'Trabzonspor',
'Trelleborg FF': 'Trelleborg',
'Trento': 'Trento',
'TSC Bačka Topola': 'TSC',
'Twente': 'Twente',
'Universidad Católica': 'U. Catolica',
'Universidad de Concepcion': 'U. De Concepcion',
'UD Ibiza': 'UD Ibiza',
'Umraniyespor': 'Umraniyespor',
'UNA Strassen': 'UNA Strassen',
'Union Cocle': 'Union Cocle',
'Pétange': 'Union Titus Petange',
'Unirea Slobozia': 'Unirea Slobozia',
'CS Universitatea Craiova': 'Univ. Craiova',
'Universidad Central': 'Universidad Central',
'Utrecht': 'Utrecht',
'Vaduz': 'Vaduz',
'Valencia': 'Valencia',
'Valladolid': 'Valladolid',
'Vancouver': 'Vancouver Whitecaps',
'Varaždin': 'Varazdin',
'Varberg FC': 'Varberg',
'Värnamo': 'Varnamo',
'Vasas': 'Vasas',
'Vasco': 'Vasco',
'Västeras SK': 'Vasteras SK',
'Vegalta Sendai': 'Vegalta Sendai',
'Vélez Sarsfield': 'Velez Sarsfield',
'Venezuela Ž-U20': 'Venezuela U20 W',
'Viborg': 'Viborg',
'Victoria Rosport': 'Victoria Rosport',
'Viktoria Köln': 'Viktoria Koln',
'Villa Dálmine': 'Villa Dalmine',
'Villa San Carlos': 'Villa San Carlos',
'Villarreal': 'Villarreal',
'Volos NFC': 'Volos',
'Vozdovac': 'Vozdovac',
'Waregem': 'Waregem',
'Bremen': 'Werder Bremen',
'West Ham Ž': 'West Ham W',
'Westerlo': 'Westerlo',
'Wil': 'Wil',
'Wollongong Wolves': 'Wollongong Wolves',
'Wolverhampton': 'Wolves',
'Western Sydney': 'WS Wanderers',
'Western Sydney W.Youth': 'WS Wanderers U21',
'Neuchatel Xamax': 'Xamax',
'FC Yokohama': 'Yokohama FC',
'Young Boys Bern': 'Young Boys',
'Zacatecoluca FC': 'Zacatecoluca',
'Zalaegerszegi': 'Zalaegerszegi',
'Zaragoza': 'Zaragoza',
'Zeledón': 'Zeledon',
'Zemun': 'Zemun',
'Zrinjski Mostar': 'Zrinjski',
'Zwickau': 'Zwickau',
'Zwolle': 'Zwolle',
}
let dctTeamsId = {}
Object.keys(dctTeamsCZToOP).forEach((key, index) => {
    dctTeamsId[dctTeamsCZToOP[key]] = 't'+ String(index).padStart(4, "0")
})